from __future__ import annotations

import csv
import io
import json
import re
from pathlib import Path
from typing import Any

from .config import load_json
from .governance import section

OUTCOME=re.compile(r"\bO-\d{3,}\b")
OPPORTUNITY=re.compile(r"\bOP-\d{3,}\b")
EXPERIMENT=re.compile(r"\bEXP-\d{3,}\b")
BET=re.compile(r"\bBET-\d{3,}\b")
MILESTONE=re.compile(r"\bM-\d{3,}\b")
PRD=re.compile(r"\bPRD-\d{3,}\b")
CHANGE=re.compile(r"\bCR-\d{3,}\b")
REVIEW=re.compile(r"\bREVIEW-\d{3,}\b")
REQUIREMENT=re.compile(r"^- (PRD-\d{3,}-R\d{2,}):\s*(.+)$",re.MULTILINE)
SPEC_CRITERION=re.compile(r"^- (SPEC-\d{3,}-A\d{2,}):\s*(.+)$",re.MULTILINE)
GENERATED="<!-- GENERATED by `python scripts/ados.py product export`; DO NOT EDIT. -->"


def _text(path:Path)->str: return path.read_text(encoding="utf-8")


def _all_text(paths:list[Path])->str: return "\n".join(_text(path) for path in paths)


def _ids(pattern:re.Pattern[str],text:str)->set[str]: return set(pattern.findall(text))


def _heading_content(text:str,name:str)->str:
    match=re.search(rf"^##+ {re.escape(name)}\s*$([\s\S]*?)(?=^##+ |\Z)",text,re.MULTILINE)
    return match.group(1).strip() if match else ""


def _require_sections(path:Path,names:tuple[str,...],root:Path)->list[str]:
    text=_text(path); return [f"{path.relative_to(root)} missing section {name}" for name in names if not _heading_content(text,name)]


def product_inventory(root:Path)->dict[str,set[str]]:
    outcome_text=_text(root/".ai/strategy/desired-outcomes.md")
    opportunity_text=_all_text([root/".ai/discovery/opportunity-tree.md",root/".ai/discovery/customer-problems.md"])
    return {
        "outcomes":_ids(OUTCOME,outcome_text),
        "opportunities":_ids(OPPORTUNITY,opportunity_text),
        "experiments":_ids(EXPERIMENT,_all_text(list((root/".ai/discovery/experiments").glob("EXP-*.md")))),
        "bets":_ids(BET,_all_text(list((root/".ai/bets").glob("BET-*.md")))),
        "milestones":_ids(MILESTONE,_all_text(list((root/".ai/milestones").glob("M-*.md")))),
        "prds":_ids(PRD,_all_text(list((root/"docs/prd").glob("PRD-*.md")))),
        "changes":_ids(CHANGE,_all_text(list((root/"docs/change-requests").glob("CR-*.md")))),
        "reviews":_ids(REVIEW,_all_text(list((root/"docs/review/review-logs").glob("REVIEW-*.md")))),
    }


def validate_product(root:Path)->list[str]:
    required=[
        ".ai/README.md",".ai/operating-rules.md",".ai/context/project-brief.md",".ai/context/glossary.md",
        ".ai/context/stakeholders.md",".ai/context/constraints.md",".ai/strategy/north-star.md",
        ".ai/strategy/product-brief.md",".ai/strategy/product-prfaq.md",".ai/strategy/desired-outcomes.md",
        ".ai/strategy/guardrails.md",".ai/strategy/roadmap.md",".ai/strategy/outcome-scorecard.md",
        ".ai/discovery/opportunity-tree.md",".ai/discovery/customer-problems.md",".ai/discovery/assumptions.md",
        ".ai/discovery/research-notes.md",".ai/wbs.md",".ai/memory/conventions.md",
        ".ai/memory/implementation-notes.md",".ai/memory/pitfalls.md","docs/change-requests/TEMPLATE.md",
        "docs/review/qa-checklist.md","docs/review/milestone-review-template.md","docs/review/release-readiness.md",
    ]
    issues=[f"required product artifact missing: {path}" for path in required if not (root/path).exists()]
    if issues: return issues
    contracts={
        ".ai/context/project-brief.md":("Problem","Users","Desired Outcome","Business Value","Constraints","Out of Scope","Definition of Done"),
        ".ai/strategy/north-star.md":("Product Purpose","Primary User","Core Job to Be Done","Product Promise","Not This"),
        ".ai/strategy/product-brief.md":("Problem","Primary User","Desired User Outcome","Business Importance","Constraints","Out of Scope","Decision Needed"),
        ".ai/strategy/product-prfaq.md":("Press Release","Internal FAQ"),
        ".ai/strategy/guardrails.md":("Must Stay True","Must Not Happen","Accepted Tradeoffs","Rejected Tradeoffs"),
        ".ai/strategy/roadmap.md":("Now","Next","Later","Notes"),
        ".ai/discovery/customer-problems.md":("Problem","Who Has It","Evidence","Frequency and Severity","Current Workaround"),
        "docs/review/release-readiness.md":("Linked Milestones","Checks","Observation Plan"),
    }
    for relative,names in contracts.items(): issues+=_require_sections(root/relative,names,root)
    inventory=product_inventory(root)
    outcome_path=root/".ai/strategy/desired-outcomes.md"
    issues+=_require_sections(outcome_path,("Outcome Statement","Metric","Baseline","Target","Time Horizon","Guardrail Metrics"),root)
    opportunity_path=root/".ai/discovery/opportunity-tree.md"
    issues+=_require_sections(opportunity_path,("Target Outcome","Opportunities","Evidence","Candidate Bets"),root)
    if not (_ids(OUTCOME,_text(opportunity_path))<=inventory["outcomes"]): issues.append("opportunity tree references an unknown outcome")
    if not section(_text(opportunity_path),"Evidence").startswith("-"): issues.append("opportunity tree requires evidence")
    for path in sorted((root/".ai/discovery/experiments").glob("EXP-*.md")):
        issues+=_require_sections(path,("Linked Outcome","Linked Opportunity","Hypothesis","Test Design","Success Threshold","Failure Signal","Result"),root)
        text=_text(path)
        if not _ids(OUTCOME,text)<=inventory["outcomes"] or not _ids(OPPORTUNITY,text)<=inventory["opportunities"]: issues.append(f"{path.relative_to(root)} has an invalid upstream link")
    for path in sorted((root/".ai/bets").glob("BET-*.md")):
        issues+=_require_sections(path,("Linked Outcome","Linked Opportunity","Hypothesis","Smallest Valuable Version","Success Signal","Kill Criteria","Advance Criteria","Status"),root)
        text=_text(path)
        if not _ids(OUTCOME,text)<=inventory["outcomes"] or not _ids(OPPORTUNITY,text)<=inventory["opportunities"]: issues.append(f"{path.relative_to(root)} has an invalid upstream link")
    validated=set()
    for path in (root/".ai/bets").glob("BET-*.md"):
        text=_text(path); identifiers=_ids(BET,text)
        if section(text,"Status")=="Validated": validated.update(identifiers)
    for path in sorted((root/"docs/prd").glob("PRD-*.md")):
        issues+=_require_sections(path,("Parent Bet","Originating Outcome","Originating Opportunity"),root)
        text=_text(path)
        if not _ids(BET,section(text,"Parent Bet"))<=validated: issues.append(f"{path.relative_to(root)} must link a validated bet")
        if not _ids(OUTCOME,section(text,"Originating Outcome"))<=inventory["outcomes"]: issues.append(f"{path.relative_to(root)} has an unknown outcome")
        if not _ids(OPPORTUNITY,section(text,"Originating Opportunity"))<=inventory["opportunities"]: issues.append(f"{path.relative_to(root)} has an unknown opportunity")
    for path in sorted((root/".ai/milestones").glob("M-*.md")):
        issues+=_require_sections(path,("Goal","Linked Bet","Included PRDs","Exit Criteria","Review Record","Status"),root)
        text=_text(path)
        if not _ids(BET,section(text,"Linked Bet"))<=validated: issues.append(f"{path.relative_to(root)} has an invalid bet")
        if not _ids(PRD,section(text,"Included PRDs"))<=inventory["prds"]: issues.append(f"{path.relative_to(root)} has an invalid PRD")
        if not _ids(REVIEW,section(text,"Review Record"))<=inventory["reviews"]: issues.append(f"{path.relative_to(root)} has an invalid review")
    for path in sorted((root/"docs/change-requests").glob("CR-*.md")):
        issues+=_require_sections(path,("Metadata","Request","Reason","Impact","Linked Artifacts","Decision","Approval","Notes"),root)
    for path in sorted((root/"docs/review/review-logs").glob("REVIEW-*.md")):
        issues+=_require_sections(path,("Metadata","Outcome Assessment","What Still Matches Intent","Drift Detected","Missing Acceptance Items","User Evidence","Risks and Reversals","Recommended Actions"),root)
        if not _ids(MILESTONE,_text(path))<=inventory["milestones"]: issues.append(f"{path.relative_to(root)} has an invalid milestone")
    command_names={path.stem for path in (root/".ai/commands").glob("*.md")}
    expected={"orient","discover","bet","specify","plan","build","review","close"}
    if command_names!=expected: issues.append(f"command set must be exactly {', '.join(sorted(expected))}")
    for relative in (".ai/strategy/roadmap.md",".ai/strategy/outcome-scorecard.md"):
        if not _ids(OUTCOME,_text(root/relative))<=inventory["outcomes"]: issues.append(f"{relative} references an unknown outcome")
    trace=load_json(root/"docs/trace/traceability.json")
    upstream={"outcome_ref":inventory["outcomes"],"opportunity_ref":inventory["opportunities"],"bet_ref":inventory["bets"],"milestone_ref":inventory["milestones"],"review_ref":inventory["reviews"]}
    for record in trace.get("records",[]):
        for field,known in upstream.items():
            if field not in record or record[field] not in known: issues.append(f"{record.get('requirement_id')} has invalid {field}")
        change=record.get("change_request_ref")
        if change is not None and change not in inventory["changes"]: issues.append(f"{record.get('requirement_id')} has invalid change_request_ref")
    return sorted(set(issues))


def render_requirements(root:Path)->str:
    lines=[GENERATED,"# Requirements Index",""]
    for path in sorted((root/"docs/prd").glob("PRD-*.md")):
        for requirement,description in REQUIREMENT.findall(_text(path)): lines.append(f"- {requirement}: {description} (source: `{path.relative_to(root)}`)")
    return "\n".join(lines)+"\n"


def render_acceptance(root:Path)->str:
    lines=[GENERATED,"# Acceptance Criteria Index",""]
    for path in sorted((root/"docs/specs").glob("SPEC-*.md")):
        for criterion,description in SPEC_CRITERION.findall(_text(path)): lines.append(f"- {criterion}: {description} (source: `{path.relative_to(root)}`)")
    return "\n".join(lines)+"\n"


def render_trace_csv(root:Path)->str:
    output=io.StringIO(); output.write("# GENERATED by `python scripts/ados.py product export`; DO NOT EDIT.\n")
    fields=["Requirement ID","Outcome ID","Opportunity ID","Bet ID","PRD","Spec","Milestone","Ticket","Change Request","Component","Test Case","Event","Metric","Review","Status","Notes"]
    writer=csv.DictWriter(output,fieldnames=fields,lineterminator="\n"); writer.writeheader()
    for record in load_json(root/"docs/trace/traceability.json")["records"]:
        writer.writerow({"Requirement ID":record["requirement_id"],"Outcome ID":record["outcome_ref"],"Opportunity ID":record["opportunity_ref"],"Bet ID":record["bet_ref"],"PRD":record["requirement_id"].split("-R")[0],"Spec":record["spec_ref"],"Milestone":record["milestone_ref"],"Ticket":record["ticket_ref"],"Change Request":record["change_request_ref"] or "","Component":record["code_ref"],"Test Case":record["test_ref"],"Event":record["telemetry_event"],"Metric":record["metric_ref"],"Review":record["review_ref"],"Status":record["status"],"Notes":record["completion_note"]})
    return output.getvalue()


def generated_views(root:Path)->dict[Path,str]:
    return {root/".ai/requirements/requirements.md":render_requirements(root),root/".ai/requirements/acceptance-criteria.md":render_acceptance(root),root/".ai/requirements/traceability.csv":render_trace_csv(root)}


def export_product_views(root:Path,check:bool=False)->list[str]:
    drift=[]
    for path,content in generated_views(root).items():
        if check:
            if not path.exists() or _text(path)!=content: drift.append(str(path.relative_to(root)))
        else:
            path.parent.mkdir(parents=True,exist_ok=True); path.write_text(content,encoding="utf-8")
    return drift


def product_metrics(root:Path)->dict[str,float|int]:
    inventory=product_inventory(root)
    prd_paths=list((root/"docs/prd").glob("PRD-*.md")); milestone_paths=list((root/".ai/milestones").glob("M-*.md")); bet_paths=list((root/".ai/bets").glob("BET-*.md"))
    prd_covered=sum(bool(_ids(BET,section(_text(p),"Parent Bet")) and _ids(OUTCOME,section(_text(p),"Originating Outcome")) and _ids(OPPORTUNITY,section(_text(p),"Originating Opportunity"))) for p in prd_paths)
    opportunity_paths=[root/".ai/discovery/opportunity-tree.md"]
    evidenced=sum(bool(section(_text(p),"Evidence").startswith("-")) for p in opportunity_paths)
    bet_valid=sum(all(section(_text(p),name) for name in ("Success Signal","Kill Criteria","Advance Criteria")) for p in bet_paths)
    reviewed=sum(bool(_ids(REVIEW,section(_text(p),"Review Record"))) for p in milestone_paths if section(_text(p),"Status")=="Complete")
    completed=sum(section(_text(p),"Status")=="Complete" for p in milestone_paths)
    return {"product_chain_coverage":prd_covered/len(prd_paths) if prd_paths else 1.0,"opportunity_evidence_coverage":evidenced/len(opportunity_paths) if opportunity_paths else 1.0,"validated_bet_rate":bet_valid/len(bet_paths) if bet_paths else 1.0,"milestone_review_coverage":reviewed/completed if completed else 1.0,"product_outcome_count":len(inventory["outcomes"])}
